# Name of this workflow
name: Test Project

# Event for treger workflow
on: [push, workflow_dispatch]

# jobs for what kind of work it should be
jobs:

    # name of the job
    test-project:

        # what mechine it neeed
        name: Run on Lunix
        runs-on: ubuntu-latest

        # steps for complete this jobs
        steps:

            # checkout for clone this project
            - name: Check
              uses: actions/checkout@v4

            # Install Node on this lunix mechine what version 20
            - name: Node install
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            # Check node version
            - name: Check node version
              run: node -v

            # Install dependency 
            - name: Install Dependency
              run: npm ci
              working-directory: frontend

            # Run text
            - name: Run text
              run: npm run test
              working-directory: frontend

    deploy-project:
        name: Deploy on lunix mechine
        runs-on: ubuntu-latest

        steps:

            - name: Check
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install dependency
              run: npm ci

            - name: Deploy project
              run: echo "Deploying ...."
            
            